/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'totalInCents' : bigint, 'items' : Array<CartItem> }
export interface CartItem {
  'productId' : string,
  'productName' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
}
export type Category = { 'food' : null } |
  { 'coldDrinks' : null } |
  { 'hotDrinks' : null } |
  { 'frappuccinos' : null };
export interface NutritionalInfo {
  'fat' : number,
  'carbs' : number,
  'calories' : bigint,
  'protein' : number,
}
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalInCents' : bigint,
  'customerId' : Principal,
  'items' : Array<OrderItem>,
  'stripeSessionId' : [] | [string],
  'estimatedPickupMinutes' : bigint,
}
export type OrderId = bigint;
export interface OrderItem {
  'productId' : string,
  'productName' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
}
export type OrderStatus = { 'preparing' : null } |
  { 'placed' : null } |
  { 'pickedUp' : null } |
  { 'ready' : null };
export interface Product {
  'id' : string,
  'nutritionalInfo' : NutritionalInfo,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : string,
  'category' : Category,
  'priceInCents' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  '_orderTransform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'addToCart' : ActorMethod<[CartItem], undefined>,
  'adminAddProduct' : ActorMethod<[Product], undefined>,
  'adminDeleteProduct' : ActorMethod<[string], undefined>,
  'adminGetAllOrders' : ActorMethod<[], Array<Order>>,
  'adminSetProductAvailability' : ActorMethod<[string, boolean], undefined>,
  'adminUpdateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'adminUpdateProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkout' : ActorMethod<[string, string], string>,
  'clearMyCart' : ActorMethod<[], undefined>,
  'confirmOrder' : ActorMethod<[string], Order>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItem' : ActorMethod<[string], [] | [Product]>,
  'getMenuItems' : ActorMethod<[], Array<Product>>,
  'getMenuItemsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getMyCart' : ActorMethod<[], Cart>,
  'getMyOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'searchMenuItems' : ActorMethod<[string], Array<Product>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCartItem' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];