/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
});
export const NutritionalInfo = IDL.Record({
  'fat' : IDL.Float64,
  'carbs' : IDL.Float64,
  'calories' : IDL.Nat,
  'protein' : IDL.Float64,
});
export const Category = IDL.Variant({
  'food' : IDL.Null,
  'coldDrinks' : IDL.Null,
  'hotDrinks' : IDL.Null,
  'frappuccinos' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'nutritionalInfo' : NutritionalInfo,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'priceInCents' : IDL.Nat,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'placed' : IDL.Null,
  'pickedUp' : IDL.Null,
  'ready' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const OrderItem = IDL.Record({
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalInCents' : IDL.Nat,
  'customerId' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'estimatedPickupMinutes' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Cart = IDL.Record({
  'totalInCents' : IDL.Nat,
  'items' : IDL.Vec(CartItem),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  '_orderTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'addToCart' : IDL.Func([CartItem], [], []),
  'adminAddProduct' : IDL.Func([Product], [], []),
  'adminDeleteProduct' : IDL.Func([IDL.Text], [], []),
  'adminGetAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'adminSetProductAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'adminUpdateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'adminUpdateProduct' : IDL.Func([Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkout' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'clearMyCart' : IDL.Func([], [], []),
  'confirmOrder' : IDL.Func([IDL.Text], [Order], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenuItem' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getMenuItems' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getMyCart' : IDL.Func([], [Cart], ['query']),
  'getMyOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
  'searchMenuItems' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCartItem' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const CartItem = IDL.Record({
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
  });
  const NutritionalInfo = IDL.Record({
    'fat' : IDL.Float64,
    'carbs' : IDL.Float64,
    'calories' : IDL.Nat,
    'protein' : IDL.Float64,
  });
  const Category = IDL.Variant({
    'food' : IDL.Null,
    'coldDrinks' : IDL.Null,
    'hotDrinks' : IDL.Null,
    'frappuccinos' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'nutritionalInfo' : NutritionalInfo,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'priceInCents' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'placed' : IDL.Null,
    'pickedUp' : IDL.Null,
    'ready' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const OrderItem = IDL.Record({
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'totalInCents' : IDL.Nat,
    'customerId' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'estimatedPickupMinutes' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Cart = IDL.Record({
    'totalInCents' : IDL.Nat,
    'items' : IDL.Vec(CartItem),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    '_orderTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'addToCart' : IDL.Func([CartItem], [], []),
    'adminAddProduct' : IDL.Func([Product], [], []),
    'adminDeleteProduct' : IDL.Func([IDL.Text], [], []),
    'adminGetAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'adminSetProductAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'adminUpdateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'adminUpdateProduct' : IDL.Func([Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkout' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'clearMyCart' : IDL.Func([], [], []),
    'confirmOrder' : IDL.Func([IDL.Text], [Order], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenuItem' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getMenuItems' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getMyCart' : IDL.Func([], [Cart], ['query']),
    'getMyOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
    'searchMenuItems' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCartItem' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };